// Every entry on the Revisions page, oldest first, with the verb the entry itself uses.
// The page lists "Silent, but warm" twice; it appears here once.

// The kind groups the verbs into families, each drawn as its own marker.
export type Kind = "gone" | "replaced" | "narrowed" | "widened" | "corrected" | "reversed";

export const KIND_OF: Record<string, Kind> = {
  RETIRED: "gone",
  RETRACTED: "gone",
  CUT: "gone",
  DROPPED: "gone",
  WITHDRAWN: "gone",
  REPLACED: "replaced",
  REBUILT: "replaced",
  NARROWED: "narrowed",
  REDUCED: "narrowed",
  SHARPENED: "narrowed",
  FROZEN: "narrowed",
  SPLIT: "narrowed",
  EXTENDED: "widened",
  WIDENED: "widened",
  LAYERED: "widened",
  CORRECTED: "corrected",
  CLARIFIED: "corrected",
  REREAD: "corrected",
  NAMED: "corrected",
  REVERSED: "reversed",
};

// [short tag, verb]
export const ENTRIES: [string, string][] = [
  ["DARK MATTER", "RETIRED"],
  ["TWO READINGS", "REPLACED"],
  ["SELECTION", "REPLACED"],
  ["WHOLE BRANCH", "REPLACED"],
  ["AXIOMS", "REBUILT"],
  ["LIVED", "SPLIT"],
  ["BORN SHARES", "RETRACTED"],
  ["OMEGA LIMIT", "CUT"],
  ["ONE VALUE", "LAYERED"],
  ["ECONOMY", "REPLACED"],
  ["AGREEMENT", "DROPPED"],
  ["THE BRIDGE", "REPLACED"],
  ["FIVE", "EXTENDED"],
  ["NO ONE HOME", "REPLACED"],
  ["SIX", "REDUCED"],
  ["OWN SENSES", "REPLACED"],
  ["ANESTHESIA", "RETIRED"],
  ["QUBIT TEST", "RETIRED"],
  ["FALSIFIED", "REPLACED"],
  ["CONFIRMED", "CORRECTED"],
  ["CONSTANT", "REPLACED"],
  ["EXACTLY ZERO", "REPLACED"],
  ["CRITICALITY", "REREAD"],
  ["LIVE CHANNEL", "SHARPENED"],
  ["EXEMPTION", "REPLACED"],
  ["CREATION", "NARROWED"],
  ["AXIOM 2", "CORRECTED"],
  ["COLLAPSE", "CORRECTED"],
  ["EXACT LINE", "REPLACED"],
  ["FALLBACK", "REPLACED"],
  ["TEST A", "FROZEN"],
  ["IDENTITY", "REPLACED"],
  ["DRIVABLE RANGE", "REPLACED"],
  ["BRANCH SEAM", "DROPPED"],
  ["PRESENCE", "REPLACED"],
  ["UNNAMED VIEW", "NAMED"],
  ["ONLY MEASURE", "REPLACED"],
  ["ONE SHAPE", "DROPPED"],
  ["CRITICAL", "WIDENED"],
  ["REALIZED WORLD", "CORRECTED"],
  ["UNLIVED REAL", "REVERSED"],
  ["WAKING", "CLARIFIED"],
  ["ETHICAL PAYOFF", "RETIRED"],
  ["SINGLE VIEW", "WITHDRAWN"],
  ["AI QUESTION", "REPLACED"],
  ["SILENT BUT WARM", "RETIRED"],
];
